Add support for offset on Aggregate (#3137)
weaviate/weaviate pull request #3277
Opened 2023-07-20 04:50 UTC by arnabguin

### What's being changed:

Add support for offset on Aggregate (#3137)

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [v] All new code is covered by tests where it is reasonable.
        - Added unit, integration and acceptance tests.
- [ ] Performance tests have been run or not necessary.

2023-07-21 06:49 UTC, arnabguin commented
agree with CLA

2023-08-23 05:09 UTC, dirkkul requested changes
Hi, thank you for your contribution! I made two comments, fi you could fix them we should be good to merge.

2023-08-23 05:09 UTC, dirkkul commented on adapters/repos/db/aggregator/grouper.go
> +	return g.topGroups[g.offset:], nil
this would probably crash if the length of the results are shorter than the offset. Could you fix that and add a test for this?

2023-08-23 05:09 UTC, dirkkul commented on adapters/repos/db/aggregations_integration_test.go
> +			assert.Equal(t, 60, res.Groups[0].Count)
could you change this test to a table-driven test? See for example test/acceptance_with_go_client/search_test.go::84

2023-09-25 06:34 UTC, closed without merging

2023-09-25 06:34 UTC, dirkkul commented
Closing this because there was no response in a while, feel free to reopen with responses to my review