pq: handle cache miss
weaviate/weaviate pull request #3335
Opened 2023-08-02 16:56 UTC by asdine

### What's being changed:

This is an attempt to handle loading compressed vectors during a cache miss.

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [x] All new code is covered by tests where it is reasonable.
- [ ] Performance tests have been run or not necessary.

2023-08-04 08:00 UTC, trengrj commented on adapters/repos/db/vector/hnsw/datasets/neurips23/data/random-clustered10000/clu-random.fbin.crop_nb_10000
Can you please remove these files and add to .gitignore?

2023-08-04 15:18 UTC, asdine commented on adapters/repos/db/vector/hnsw/datasets/neurips23/data/random-clustered10000/clu-random.fbin.crop_nb_10000
Good catch, I didn't realize I added them to the branch! I have removed them and I will add them to .gitignore in the other PR (since they are not related to this one)

2023-08-07 05:55 UTC, abdelr requested changes

2023-08-07 05:55 UTC, abdelr commented on adapters/repos/db/vector/hnsw/compress.go
> +	}
In the case we are using `cosine` distance we need to normalise the vector before compressing it.

2023-08-15 06:00 UTC, abdelr approved these changes
Looks good. Not a must, but maybe we want to have some more cosine tests in our pipelines to detect things like vectors brought back without normalisation.

2023-08-15 08:18 UTC, asdine commented
Good idea. It's a bit more involved as I need to make the thunk configurable, so I'll do it in a separate PR.

2023-08-15 08:19 UTC, merged