Use context for requests
weaviate/weaviate pull request #3538
Opened 2023-09-15 20:26 UTC by alexandear

### What's being changed:

This PR replaces `http.NewRequest` with `http.NewRequestWithContext` where possible.

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [ ] All new code is covered by tests where it is reasonable.
- [ ] Performance tests have been run or not necessary.

2023-09-16 07:13 UTC, alexandear commented
Agree with CLA.

2023-09-25 07:24 UTC, redouan-rhazouani requested changes

2023-09-25 07:24 UTC, redouan-rhazouani commented on adapters/clients/replication.go
> +func newHttpReplicaCMD(ctx context.Context, host, cmd, index, shard, requestId string, body io.Reader) (*http.Request, error) {
This function doesn't require a context parameter since the calling function handles the context management.

2023-09-25 07:24 UTC, redouan-rhazouani commented on adapters/clients/cluster_backups.go
> +	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, url.String(), bytes.NewReader(b))
The function is almost instantaneous and doesn't require a context.

2023-09-25 12:09 UTC, closed without merging