fix: support partially deleted obj during async replication
weaviate/weaviate pull request #5314
Opened 2024-07-05 20:24 UTC by jeroiraz

### What's being changed:

### Review checklist

- [ ] Documentation has been updated, if necessary. Link to changed documentation:
- [ ] Chaos pipeline run or not necessary. Link to pipeline:
- [ ] All new code is covered by tests where it is reasonable.
- [ ] Performance tests have been run or not necessary.

2024-07-05 22:45 UTC, parkerduckworth approved these changes

2024-07-08 08:47 UTC, jfrancoa commented
I did the very same test with this branch and it threw a new panic in the nodes which were up after starting up the node that was down (a delete took place while it was down):
```
DEBU[0065] raft failed to contact                        action=raft fields.time=16.155771542s server-id=weaviate-2
INFO[0066] raft updating configuration                   action=raft command=AddVoter server-addr="192.168.86.22:8304" server-id=weaviate-2 servers="[[{Suffrage:Voter ID:weaviate-0 Address:192.168.86.22:8300} {Suffrage:Voter ID:weaviate-1 Address:192.168.86.22:8302} {Suffrage:Voter ID:weaviate-2 Address:192.168.86.22:8304}]]"
INFO[0070] raft pipelining replication                   action=raft peer="{Voter weaviate-2 192.168.86.22:8304}"
2024/07/08 10:45:42 http: panic serving 192.168.86.22:64948: runtime error: index out of range [1] with length 0
goroutine 14863 [running]:
net/http.(*conn).serve.func1()
	/Users/jfrancoa/go/src/net/http/server.go:1868 +0xb0
panic({0x10264fc00?, 0x14003b1c078?})
	/Users/jfrancoa/go/src/runtime/panic.go:926 +0x26c
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*Memtable).newCursorWithSecondaryIndex.func2(0x6?)
	/Users/jfrancoa/repos/weaviate/adapters/repos/db/lsmkv/cursor_memtable_replace.go:101 +0x54
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*memtableCursor).posLargerThanEqual(0x14003cd3900, {0x14003b1c060, 0x18, 0x18})
	/Users/jfrancoa/repos/weaviate/adapters/repos/db/lsmkv/cursor_memtable_replace.go:142 +0x80
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*memtableCursor).seek(0x14003cd3900, {0x14003b1c060, 0x18, 0x18})
	/Users/jfrancoa/repos/weaviate/adapters/repos/db/lsmkv/cursor_memtable_replace.go:128 +0x78
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*CursorReplace).seekAll(0x140033a9dd0, {0x14003b1c060, 0x18, 0x18})
	/Users/jfrancoa/repos/weaviate/adapters/repos/db/lsmkv/cursor_bucket_replace.go:111 +0xb0
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*CursorReplace).Seek(0x140060285a0?, {0x14003b1c060?, 0x140072577e8?, 0x1011c9694?})
	/Users/jfrancoa/repos/weaviate/adapters/repos/db/lsmkv/cursor_bucket_replace.go:212 +0x24
github.com/weaviate/weaviate/adapters/repos/db.(*Shard).ObjectDigestsByTokenRange(0x14003a260f0?, {0x1027a00f0?, 0x14003b7d810?}, 0xa87d2b30e0e4caf2, 0xa87dcba27ac3a398, 0x64)
	/Users/jfrancoa/repos/weaviate/adapters/repos/db/shard_read.go:153 +0xfc
github.com/weaviate/weaviate/adapters/repos/db.(*LazyLoadShard).ObjectDigestsByTokenRange(0x14003a260f0, {0x1027a00f0, 0x14003b7d810}, 0x1400708aaa5?, 0xc?, 0x1007122a8?)
	/Users/jfrancoa/repos/weaviate/adapters/repos/db/shard_lazyloader.go:295 +0x7c
github.com/weaviate/weaviate/adapters/repos/db.(*Index).DigestObjectsInTokenRange(0x1022dd000?, {0x1027a00f0, 0x14003b7d810}, {0x1400708aaa5, 0xc}, 0x101264e20?, 0x140033a9c20?, 0x1022dd000?)
	/Users/jfrancoa/repos/weaviate/adapters/repos/db/replication.go:433 +0xbc
github.com/weaviate/weaviate/usecases/replica.(*RemoteReplicaIncoming).DigestObjectsInTokenRange(0x14007896400?, {0x1027a00f0, 0x14003b7d810}, {0x1400708aa97?, 0x14003b1c018?}, {0x1400708aaa5, 0xc}, 0x1008ce520?, 0x14003e6ae00?, 0x14007257970?)
	/Users/jfrancoa/repos/weaviate/usecases/replica/remote_incoming.go:215 +0xa0
github.com/weaviate/weaviate/adapters/handlers/rest/clusterapi.(*replicatedIndices).getObjectsDigestsInTokenRange.func1({0x10279b2d0, 0x14003b01500}, 0x14006e19800)
	/Users/jfrancoa/repos/weaviate/adapters/handlers/rest/clusterapi/indices_replicas.go:450 +0x180
net/http.HandlerFunc.ServeHTTP(0x14003fe72f0?, {0x10279b2d0?, 0x14003b01500?}, 0x1008da1b8?)
	/Users/jfrancoa/go/src/net/http/server.go:2136 +0x38
github.com/weaviate/weaviate/adapters/handlers/rest/clusterapi.(*replicatedIndices).Indices.(*replicatedIndices).indicesHandler.func1({0x10279b2d0, 0x14003b01500}, 0x14006e19800)
	/Users/jfrancoa/repos/weaviate/adapters/handlers/rest/clusterapi/indices_replicas.go:123 +0x148
net/http.HandlerFunc.ServeHTTP(0x14003cd38ec?, {0x10279b2d0?, 0x14003b01500?}, 0x14007257af0?)
	/Users/jfrancoa/go/src/net/http/server.go:2136 +0x38
net/http.(*ServeMux).ServeHTTP(0x10?, {0x10279b2d0, 0x14003b01500}, 0x14006e19800)
	/Users/jfrancoa/go/src/net/http/server.go:2514 +0x144
net/http.serverHandler.ServeHTTP({0x1027934c0?}, {0x10279b2d0?, 0x14003b01500?}, 0x6?)
	/Users/jfrancoa/go/src/net/http/server.go:2938 +0xbc
net/http.(*conn).serve(0x140033a9830, {0x1027a00b8, 0x14003fe74d0})
	/Users/jfrancoa/go/src/net/http/server.go:2009 +0x518
created by net/http.(*Server).Serve in goroutine 147
	/Users/jfrancoa/go/src/net/http/server.go:3086 +0x4cc
2024/07/08 10:45:42 http: panic serving 192.168.86.22:64949: runtime error: index out of range [1] with length 0
goroutine 15045 [running]:
net/http.(*conn).serve.func1()
	/Users/jfrancoa/go/src/net/http/server.go:1868 +0xb0
panic({0x10264fc00?, 0x14003b1c2e8?})
	/Users/jfrancoa/go/src/runtime/panic.go:926 +0x26c
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*Memtable).newCursorWithSecondaryIndex.func2(0x2?)
	/Users/jfrancoa/repos/weaviate/adapters/repos/db/lsmkv/cursor_memtable_replace.go:101 +0x54
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*memtableCursor).posLargerThanEqual(0x14005842140, {0x14003b1c2d0, 0x18, 0x18})
	/Users/jfrancoa/repos/weaviate/adapters/repos/db/lsmkv/cursor_memtable_replace.go:142 +0x80
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*memtableCursor).seek(0x14005842140, {0x14003b1c2d0, 0x18, 0x18})
	/Users/jfrancoa/repos/weaviate/adapters/repos/db/lsmkv/cursor_memtable_replace.go:128 +0x78
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*CursorReplace).seekAll(0x14003418750, {0x14003b1c2d0, 0x18, 0x18})
	/Users/jfrancoa/repos/weaviate/adapters/repos/db/lsmkv/cursor_bucket_replace.go:111 +0xb0
github.com/weaviate/weaviate/adapters/repos/db/lsmkv.(*CursorReplace).Seek(0x14005afd7a0?, {0x14003b1c2d0?, 0x140072577e8?, 0x1011c9694?})
	/Users/jfrancoa/repos/weaviate/adapters/repos/db/lsmkv/cursor_bucket_replace.go:212 +0x24
github.com/weaviate/weaviate/adapters/repos/db.(*Shard).ObjectDigestsByTokenRange(0x14003a26000?, {0x1027a00f0?, 0x14003b7def0?}, 0x2e5faaa649258bcd, 0x2e6065ff302c5477, 0x64)
	/Users/jfrancoa/repos/weaviate/adapters/repos/db/shard_read.go:153 +0xfc
github.com/weaviate/weaviate/adapters/repos/db.(*LazyLoadShard).ObjectDigestsByTokenRange(0x14003a26000, {0x1027a00f0, 0x14003b7def0}, 0x1400708b285?, 0xc?, 0x1007122a8?)
	/Users/jfrancoa/repos/weaviate/adapters/repos/db/shard_lazyloader.go:295 +0x7c
github.com/weaviate/weaviate/adapters/repos/db.(*Index).DigestObjectsInTokenRange(0x1022dd000?, {0x1027a00f0, 0x14003b7def0}, {0x1400708b285, 0xc}, 0x101264e20?, 0x140034186c0?, 0x1022dd000?)
	/Users/jfrancoa/repos/weaviate/adapters/repos/db/replication.go:433 +0xbc
github.com/weaviate/weaviate/usecases/replica.(*RemoteReplicaIncoming).DigestObjectsInTokenRange(0x14007897800?, {0x1027a00f0, 0x14003b7def0}, {0x1400708b277?, 0x14003b1c288?}, {0x1400708b285, 0xc}, 0x1008ce520?, 0x14003e6ae00?, 0x14007257970?)
	/Users/jfrancoa/repos/weaviate/usecases/replica/remote_incoming.go:215 +0xa0
github.com/weaviate/weaviate/adapters/handlers/rest/clusterapi.(*replicatedIndices).getObjectsDigestsInTokenRange.func1({0x10279b2d0, 0x14003b01dc0}, 0x14007c04500)
	/Users/jfrancoa/repos/weaviate/adapters/handlers/rest/clusterapi/indices_replicas.go:450 +0x180
net/http.HandlerFunc.ServeHTTP(0x14003fe72f0?, {0x10279b2d0?, 0x14003b01dc0?}, 0x1008da1b8?)
	/Users/jfrancoa/go/src/net/http/server.go:2136 +0x38
github.com/weaviate/weaviate/adapters/handlers/rest/clusterapi.(*replicatedIndices).Indices.(*replicatedIndices).indicesHandler.func1({0x10279b2d0, 0x14003b01dc0}, 0x14007c04500)
	/Users/jfrancoa/repos/weaviate/adapters/handlers/rest/clusterapi/indices_replicas.go:123 +0x148
net/http.HandlerFunc.ServeHTTP(0x1400584212c?, {0x10279b2d0?, 0x14003b01dc0?}, 0x14007257af0?)
	/Users/jfrancoa/go/src/net/http/server.go:2136 +0x38
net/http.(*ServeMux).ServeHTTP(0x10?, {0x10279b2d0, 0x14003b01dc0}, 0x14007c04500)
	/Users/jfrancoa/go/src/net [...]

2024-07-08 11:38 UTC, parkerduckworth requested changes
Need to resolve this panic before merging

2024-07-08 18:12 UTC, parkerduckworth commented
@jeroiraz @jfrancoa I've opened #5324 to address the panic above. The main idea is that in some scenarios, we can see a resurrected node stuck in an infinite loop attempting to propagate deleted objects. In these cases, the missing object will need to be reintroduced into the cluster. This limitation should be removed once async replication supports delete operations

2024-07-09 21:27 UTC, parkerduckworth approved these changes

2024-07-09 21:27 UTC, merged